### ISSUE TITLE
Call for heating blocks 1-wire network on reactive branch

### ISSUE THREAD

**Issue by marcass** [home-climate-control/dz#252] opened 2022-11-20 18:51 UTC
Reactive branch working well using a 1-wire network until heating is called for. Then stdout has messages like the following:
```
07:06:54,508 WARN SwitchableHvacDevice boundedElastic-1 [] fanSpeed=>0 should not be issued to this device in heating mode, kick the maintainer to fix #222 (command={mode=null, demand=2.000431575, fanSpeed=2.000431575})
```

The android app has all zones red and is not responsive and the instance has to be killed in a separate terminal with a "kill -9 <process>"

Kicking maintainer as instructed

Marcus

**Comment by climategadgets** [comment] 2023-02-04 07:35
The error message itself belongs to #222 . This issue is likely a dupe of #223 , will be fixed there.

**Closed by climategadgets** 2023-02-04 07:35 UTC
